### ISSUE TITLE
Questions About Training and Results in PointTransformerV3

### ISSUE THREAD

**Issue by xiaosa269** [Pointcept/PointTransformerV3#117]
Hello,  thank you very much for your excellent work! I am a beginner, and I have a few questions I would like to ask:

1.How can I use the PPT method for training? How should I configure and enable it?
2.When I start training normally, will it save the tensorboard logs? If so, how can I view them? Additionally, how can I check the contents of the .sun files?
3.In your paper, you only included the mIoU value for the SemanticKITTI dataset. Where can I find the detailed values for each label?

Thank you for your help, and I wish you success in your research!

**Comment by Gofinge** [comment]
> How can I use the PPT method for training?

Usually, I will just copy the default config file for PPT and modify it to support the change you want to make. For example, if you doing some research related to the backbone, just replace the backbone config to the one you want.

> When I start training normally, will it save the tensorboard logs?

Yes, in exp/dataset/exp_name

> If so, how can I view them? 

Google how to load tenserboard files in a specific folder.

> how can I check the contents of the .sun files?

Sorry, I don't know what means .sun files.

> Where can I find the detailed values for each label?

Not available now, as I cannot access the original experiment record due to a change of internship. I will take a look at the reproduce later.
